# Generated by Django 3.0.3 on 2020-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_img_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_ID',
            field=models.IntegerField(default=0),
        ),
    ]
