# Generated by Django 3.0.3 on 2020-03-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
